<a href="https://colab.research.google.com/github/lukmanaj/ArewaDS-Deep-Learning/blob/main/Part_1_Deep_Learning_with_Pytorch/week1/week_1_exercises_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##GPU PART OF WEEK ONE ASSIGNMENT

First, import PyTorch


In [1]:
import torch

In [2]:
# checking the version
torch.__version__

'2.1.0+cu121'

First,checking for GPU

In [3]:
# Check if CUDA is available
cuda_available = torch.cuda.is_available()

if cuda_available:
    # Get CUDA version from PyTorch
    cuda_version = torch.version.cuda

    # Get the number of CUDA devices available
    num_devices = torch.cuda.device_count()

    # Print CUDA details
    print(f"CUDA is available: {cuda_available}")
    print(f"CUDA version: {cuda_version}")
    print(f"Number of CUDA devices: {num_devices}")

    # Detail of each CUDA device
    for i in range(num_devices):
        print(torch.cuda.get_device_properties(i))
else:
    print("CUDA is not available on this system.")


CUDA is available: True
CUDA version: 12.1
Number of CUDA devices: 1
_CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15102MB, multi_processor_count=40)


## Exercises 6 - 10

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [5]:

torch.manual_seed(1234)
tensor1 = torch.randn(2, 3)
tensor2 = torch.randn(2, 3)

tensor1 = tensor1.to('cuda')
tensor2 = tensor2.to('cuda')
print(f'tensor 1:\n {tensor1} \n tensor 2: \n {tensor2}')

tensor 1:
 tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]], device='cuda:0') 
 tensor 2: 
 tensor([[ 0.2310,  0.6931, -0.2669],
        [ 2.1785,  0.1021, -0.2590]], device='cuda:0')


7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [6]:
tensor_mult = torch.matmul(tensor1,tensor2.T)
tensor_mult

tensor([[ 0.5595,  0.4036],
        [-0.5087,  0.2792]], device='cuda:0')

8. Find the maximum and minimum values of the output of 7.

In [7]:
torch.max(tensor_mult)

tensor(0.5595, device='cuda:0')

In [8]:
torch.min(tensor_mult)

tensor(-0.5087, device='cuda:0')

9. Find the maximum and minimum index values of the output of 7.

In [9]:
torch.argmax(tensor_mult)


tensor(0, device='cuda:0')

In [10]:
torch.argmin(tensor_mult)


tensor(2, device='cuda:0')

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [17]:
torch.manual_seed(7)
random_tensor = torch.rand(1,1,1,10)
print(random_tensor)
print(random_tensor.shape)

# remove all 1 dimensions
reduced_tensor = random_tensor.squeeze()
print(reduced_tensor)
print(reduced_tensor.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
