## Arewa DataScience Academy
### Deep Learning Cohort 1.0

### WEEK 1 Exercises

#### Name : Lukman Aliyu Jibril
#### email: lukman.j.aliyu@gmail.com

### Exercises:
Please, see week 1 exercises from [**Learn PyTorch for Deep Learning**: 00. Pytorch Fundamentals](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [1]:
# imports
import torch

In [2]:
torch.__version__

'2.0.1'

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda

Done. I read and understood the materials in the section of the PyTorch documentation.

2. Create a random tensor with shape (7, 7).

In [4]:
rand_tensor = torch.rand(7,7)
rand_tensor

tensor([[0.5420, 0.8892, 0.8609, 0.8307, 0.8839, 0.3955, 0.6012],
        [0.4193, 0.1745, 0.3633, 0.4594, 0.5834, 0.4887, 0.5335],
        [0.4020, 0.9194, 0.2350, 0.8012, 0.8353, 0.1232, 0.4247],
        [0.6837, 0.9456, 0.2623, 0.1814, 0.6124, 0.3858, 0.9321],
        [0.2306, 0.1554, 0.5702, 0.9792, 0.2504, 0.9928, 0.0906],
        [0.7664, 0.4865, 0.4934, 0.5516, 0.3181, 0.2998, 0.5200],
        [0.4339, 0.1896, 0.8059, 0.1994, 0.0530, 0.5630, 0.7949]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [7]:
rand_tensor2 = torch.rand(1,7)
rand_tensor_mult = torch.matmul(rand_tensor,rand_tensor2.T)
rand_tensor_mult

tensor([[3.1201],
        [1.9954],
        [2.5276],
        [2.5847],
        [2.1276],
        [2.2072],
        [1.7750]])

4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [13]:
RANDOM_SEED=0 
torch.manual_seed(seed=RANDOM_SEED) 

rand_tensor = torch.rand(7,7)
rand_tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [14]:
torch.random.manual_seed(seed=RANDOM_SEED) 
rand_tensor = torch.rand(7,7)
rand_tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [15]:
torch.random.manual_seed(seed=RANDOM_SEED) 
rand_tensor2 = torch.rand(1,7)
rand_tensor_mult = torch.matmul(rand_tensor,rand_tensor2.T)
rand_tensor_mult

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

The numbers remain the same so long as I reset the random seed before calling `.rand()` again

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [16]:
torch.cuda.manual_seed(1234)

In [18]:
# checking if I have cuda on my laptop

# Check if CUDA is available
cuda_available = torch.cuda.is_available()

if cuda_available:
    # Get CUDA version from PyTorch
    cuda_version = torch.version.cuda
    
    # Get the number of CUDA devices available
    num_devices = torch.cuda.device_count()
    
    # Print CUDA details
    print(f"CUDA is available: {cuda_available}")
    print(f"CUDA version: {cuda_version}")
    print(f"Number of CUDA devices: {num_devices}")

    # Detail of each CUDA device
    for i in range(num_devices):
        print(torch.cuda.get_device_properties(i))
else:
    print("CUDA is not available on this system.")


CUDA is not available on this system.


Unfortunately, as expected, I do not have GPU on my laptop. This is the end of this attempt on this device. I continue the rest on [colab](https://github.com/lukmanaj/ArewaDS-Deep-Learning/blob/main/Part_1_Deep_Learning_with_Pytorch/week1/week_1_exercises_part2.ipynb).

### Additional Exercise